/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Controladores.ControlFormularios;
import Controladores.classAguasobrante;
import Controladores.classDisenio;
import Controladores.classMedidor;
import Controladores.classusuario;
import static Formularios.FrmPagosAsistemcia.lblfecha;
import entidades.Aguasobrante;
import entidades.Medidor;
import entidadesCruds.exceptions.IllegalOrphanException;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Marco
 */
public class FrmAguasobrante extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmMedidor
     */
    classAguasobrante cm = new classAguasobrante();
    classusuario cu = new classusuario();

    public FrmAguasobrante() {
        initComponents();
        inicio();

    }

    ControlFormularios cf;
    
    int clic_tabla = 0;

    private void inicio() {
        limpiar();

        Dimension desktopSize = FrmPrincipal.jDesktopPane1.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, 4);
        

        cm.cargarTablaAguasobrante(jTable1);
        ocultar();
        Date fechaActual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String hoy = formato.format(fechaActual);
        lblfecha.setText(hoy);
        lblIdaguasobrante.setVisible(true);
        jLabel1.setVisible(false);
        lblIdUsuario.setToolTipText(classDisenio.txthtml("Numero de usuario, formulario usuario"));
        txtUsuarioCed.setToolTipText(classDisenio.txthtml("Numero de cedula del usuario"));
        txtNombre.setToolTipText(classDisenio.txthtml("Nombre del usuario"));
        txtCodigoaguasobrante.setToolTipText(classDisenio.txthtml("Ingrese el numero del medidor"));
        comboEstado.setToolTipText(classDisenio.txthtml("seleccione el estado de medidor"));
        txtvalorConexion.setToolTipText(classDisenio.txthtml("Ingrese valor de conexion de un usuario nuevo"));
        jTextField1.setToolTipText(classDisenio.txthtml("Seleccion busquda por apellido y luego digite el metodo de busqueda"));
        jTable1.setToolTipText(classDisenio.tablahtml("Lista de medidores"));
        
        txtSector.setToolTipText(classDisenio.txthtml("Sector"));
        txtReferencia.setToolTipText(classDisenio.txthtml("Referencia / cerca de ..."));
        txtObservacion.setToolTipText(classDisenio.txthtml("Descripcion de la conexion"));
    }

    public void mostrar() {
        txtUsuarioCed.setEnabled(true);
        txtvalorConexion.setEnabled(true);
        txtCodigoaguasobrante.setEditable(true);
        btnNuevo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnElimnar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        jTable1.setEnabled(false);
        
        txtSector.setEnabled(true);
        txtReferencia.setEnabled(true);
        txtObservacion.setEnabled(true);

    }

    public void ocultar() {
        txtUsuarioCed.setEnabled(false);
        txtvalorConexion.setEnabled(false);
        txtCodigoaguasobrante.setEditable(false);
        btnNuevo.setEnabled(true);
        btnEditar.setEnabled(true);
        btnElimnar.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        jTable1.setEnabled(true);
        
        txtSector.setEnabled(false);
        txtReferencia.setEnabled(false);
        txtObservacion.setEnabled(false);
    }

    public void limpiar() {

        txtNombre.setText("");
        txtUsuarioCed.setText("");
        txtCodigoaguasobrante.setText("");
        lblIdaguasobrante.setText("");
        lblIdUsuario.setText("");
        txtvalorConexion.setText("");
        
        txtSector.setText("");
        txtReferencia.setText("");
        txtObservacion.setText("");
//        lblIdUsuario.setVisible(false);
//        jLabel8.setVisible(false);
//         lblIdmedidor.setVisible(false);
//        jLabel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBusqueda = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        btnNuevo = new org.edisoncor.gui.button.ButtonNice();
        btnGuardar = new org.edisoncor.gui.button.ButtonNice();
        btnEditar = new org.edisoncor.gui.button.ButtonNice();
        btnElimnar = new org.edisoncor.gui.button.ButtonNice();
        btnCancelar = new org.edisoncor.gui.button.ButtonNice();
        mensaje = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEditar1 = new org.edisoncor.gui.button.ButtonNice();
        lblfecha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIdaguasobrante = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoaguasobrante = new javax.swing.JTextField();
        txtUsuarioCed = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        txtvalorConexion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSector = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }};
            jTextField1 = new javax.swing.JTextField();
            jLabel7 = new javax.swing.JLabel();
            rdbtodos = new javax.swing.JRadioButton();
            rdbApellidosN = new javax.swing.JRadioButton();

            setBackground(new java.awt.Color(255, 255, 255));
            setClosable(true);
            setIconifiable(true);
            setMaximizable(true);
            setResizable(true);
            setTitle("FORMULARIO DE USUARIOS DE AGUA SOBRANTE");

            jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            btnNuevo.setBackground(new java.awt.Color(0, 102, 255));
            btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
            btnNuevo.setText("NUEVO");
            btnNuevo.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.ROUND_LEFT);
            btnNuevo.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnNuevo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnNuevoActionPerformed(evt);
                }
            });

            btnGuardar.setBackground(new java.awt.Color(0, 102, 255));
            btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
            btnGuardar.setText("GUARDAR");
            btnGuardar.setEnabled(false);
            btnGuardar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
            btnGuardar.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnGuardar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGuardarActionPerformed(evt);
                }
            });

            btnEditar.setBackground(new java.awt.Color(0, 102, 255));
            btnEditar.setForeground(new java.awt.Color(255, 255, 255));
            btnEditar.setText("EDITAR");
            btnEditar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
            btnEditar.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnEditar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEditarActionPerformed(evt);
                }
            });

            btnElimnar.setBackground(new java.awt.Color(0, 102, 255));
            btnElimnar.setForeground(new java.awt.Color(255, 255, 255));
            btnElimnar.setText("ELIMINAR");
            btnElimnar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
            btnElimnar.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnElimnar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnElimnarActionPerformed(evt);
                }
            });

            btnCancelar.setBackground(new java.awt.Color(0, 102, 255));
            btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
            btnCancelar.setText("CANCELAR");
            btnCancelar.setEnabled(false);
            btnCancelar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.ROUND_RIGHT);
            btnCancelar.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelarActionPerformed(evt);
                }
            });

            mensaje.setForeground(new java.awt.Color(204, 0, 0));

            jLabel6.setText("Agregar Nuevo Usuario");

            btnEditar1.setBackground(new java.awt.Color(0, 102, 255));
            btnEditar1.setForeground(new java.awt.Color(255, 255, 255));
            btnEditar1.setText("+");
            btnEditar1.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
            btnEditar1.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnEditar1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEditar1ActionPerformed(evt);
                }
            });

            lblfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            lblfecha.setText("jLabel14");

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnElimnar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnElimnar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(lblfecha)))))
            );

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Nuevo Usuario de Agua Sobrante"));

            jLabel1.setText("id:");

            jLabel2.setText("Cedula:");

            lblIdaguasobrante.setText("jLabel1");

            jLabel5.setText("Codigo usuario");

            txtCodigoaguasobrante.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtCodigoaguasobranteKeyTyped(evt);
                }
            });

            txtUsuarioCed.setBorder(javax.swing.BorderFactory.createTitledBorder("Presione una Tecla dentro de este campo"));
            txtUsuarioCed.setEnabled(false);
            txtUsuarioCed.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtUsuarioCedKeyTyped(evt);
                }
            });

            txtNombre.setEnabled(false);

            jLabel4.setText("Nombre:");

            comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVO", "INACTIVO" }));

            jLabel8.setText("Numero de Usuario:");

            lblIdUsuario.setText("jLabel9");

            label.setText("Estado:");

            txtvalorConexion.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    txtvalorConexionKeyReleased(evt);
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtvalorConexionKeyTyped(evt);
                }
            });

            jLabel9.setText("Monto conexion:");

            jLabel10.setText("USD");

            jLabel11.setText("Sector:");

            txtSector.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    txtSectorKeyReleased(evt);
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtSectorKeyTyped(evt);
                }
            });

            jLabel12.setText("Referencia:");

            txtReferencia.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    txtReferenciaKeyReleased(evt);
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtReferenciaKeyTyped(evt);
                }
            });

            jLabel13.setText("Observacion:");

            txtObservacion.setColumns(20);
            txtObservacion.setRows(5);
            jScrollPane2.setViewportView(txtObservacion);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblIdaguasobrante))
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUsuarioCed)
                                .addComponent(txtNombre)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblIdUsuario))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 2, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txtCodigoaguasobrante, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSector)
                                .addComponent(txtReferencia, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtvalorConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jScrollPane2))))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblIdaguasobrante)
                        .addComponent(jLabel8)
                        .addComponent(lblIdUsuario))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtUsuarioCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoaguasobrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label)
                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtvalorConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(89, Short.MAX_VALUE))
            );

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de usuarios existentes"));

            jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jTable1.setRowHeight(25);
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTable1KeyReleased(evt);
                }
            });
            jScrollPane1.setViewportView(jTable1);

            jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField1KeyReleased(evt);
                }
            });

            jLabel7.setText("Buscar:");

            grupoBusqueda.add(rdbtodos);
            rdbtodos.setSelected(true);
            rdbtodos.setText("Todos");
            rdbtodos.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    rdbtodosActionPerformed(evt);
                }
            });

            grupoBusqueda.add(rdbApellidosN);
            rdbApellidosN.setText("Apellidos - Nombres");
            rdbApellidosN.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    rdbApellidosNActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(rdbtodos)
                    .addGap(18, 18, 18)
                    .addComponent(rdbApellidosN)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1))
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbtodos)
                        .addComponent(rdbApellidosN))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        txtUsuarioCed.setEnabled(true);
        mostrar();
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

//        float saldo = cm.buscarMedidorNumM(Integer.valueOf(txtMedidor.getText())).getSaldo();
//        if (saldo != 200) {
//            txtvalorConexion.setText(saldo + "");
//            txtvalorConexion.setEnabled(false);
//        } else {
//            txtvalorConexion.setEnabled(true);
//        }
        mostrar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        ocultar();
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed

        this.setVisible(false);
        FrmUsuario us = new FrmUsuario();

        cf = new ControlFormularios();
        cf.ControlaInstancia(us);

    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {

            int idUsuario = Integer.valueOf(lblIdUsuario.getText());
            int codigoAguasobrante = Integer.valueOf(txtCodigoaguasobrante.getText());
            String estado = comboEstado.getSelectedItem().toString();
            float valorConx = Float.valueOf(txtvalorConexion.getText());
            
            String sector = txtSector.getText();
            String referencia = txtReferencia.getText();
            String observacion = txtObservacion.getText();
            
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            Date fechaActual = formato.parse(lblfecha.getText());
            
            if (lblIdaguasobrante.getText().equals("")) {
                int i = JOptionPane.showConfirmDialog(this, "¿Realmente desea Registrar?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    cm.guardarAguasobrante(idUsuario, sector, referencia, observacion, codigoAguasobrante, estado, valorConx, fechaActual);
                    cm.cargarTablaAguasobrante(jTable1);
                    limpiar();
                    ocultar();
                }

            } else if (!lblIdaguasobrante.getText().equals("")) {
                int i = JOptionPane.showConfirmDialog(this, "¿Realmente desea Modificar?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    int idmed = Integer.valueOf(lblIdaguasobrante.getText());
                    cm.modificarAguasobrante(idmed, idUsuario,sector, referencia, observacion, codigoAguasobrante, estado, valorConx);
                    cm.cargarTablaAguasobrante(jTable1);
                    limpiar();
                    ocultar();
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnElimnarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimnarActionPerformed
        try {
            int i = JOptionPane.showConfirmDialog(this, "¿Realmente desea Eliminar?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                //cm.eliminarMedidor(Integer.valueOf(lblIdaguasobrante.getText()));
                cm.cargarTablaAguasobrante(jTable1);
                JOptionPane.showMessageDialog(null, "Eliminado");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Proceso No Realizado!.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnElimnarActionPerformed

    private void txtUsuarioCedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioCedKeyTyped

        if (txtUsuarioCed.getText().equals("")) {
            FrmListaUsuarioSinAguasobrante bu = new FrmListaUsuarioSinAguasobrante();
            bu.setVisible(true);
        }
    }//GEN-LAST:event_txtUsuarioCedKeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String cadena = (jTextField1.getText()).toUpperCase();
        jTextField1.setText(cadena);
        if (rdbApellidosN.isSelected() == true) {
            cm.cargarTablaApellidosNombres(jTextField1.getText(), jTable1);
        } else {
            cm.cargarTablaAguasobrante(jTable1);
        }

    }//GEN-LAST:event_jTextField1KeyReleased

    private void rdbtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtodosActionPerformed
        // TODO add your handling code here:
        cm.cargarTablaAguasobrante(jTable1);
        jTextField1.setText("");
    }//GEN-LAST:event_rdbtodosActionPerformed

    private void rdbApellidosNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbApellidosNActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_rdbApellidosNActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        /*
        try {
            int n = jTable1.getSelectedRow();
            int id = Integer.valueOf(jTable1.getValueAt(n, 0).toString());
            Medidor med= cm.buscarMedidorIdUsuario(id);
            
            lblIdaguasobrante.setText(jTable1.getValueAt(n, 0).toString());
            txtUsuarioCed.setText(jTable1.getValueAt(n, 1).toString());
            txtNombre.setText(jTable1.getValueAt(n, 2).toString());
            txtMedidor.setText(med.getNummedidor().toString());

            txtSerie.setText(jTable1.getValueAt(n, 4).toString());
            comboEstado.setSelectedItem(jTable1.getValueAt(n, 5).toString());
            lblIdUsuario.setText(med.getIdusuario().getIdusuario().toString());
            txtUsuarioCed.setEnabled(false);
            txtvalorConexion.setText(med.getValorporconexion().toString());
            txtSaldo.setText(med.getSaldo().toString());
            
        } catch (Exception e) {
        }
        */

    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            
            int n = jTable1.getSelectedRow();
            int id = Integer.valueOf(jTable1.getValueAt(n, 0).toString());
            Aguasobrante med= cm.buscarAguasobranteId(id);
            
            lblIdaguasobrante.setText(jTable1.getValueAt(n, 0).toString());
            txtUsuarioCed.setText(jTable1.getValueAt(n, 3).toString());
            txtNombre.setText(jTable1.getValueAt(n, 4).toString());
            txtCodigoaguasobrante.setText(jTable1.getValueAt(n, 7).toString());
            //txtMedidor.setText(med.getNummedidor().toString());

            comboEstado.setSelectedItem(jTable1.getValueAt(n, 5).toString());
            lblIdUsuario.setText(med.getIdusuario().getIdusuario().toString());
            txtUsuarioCed.setEnabled(false);
            txtvalorConexion.setText(med.getValorporconexion().toString());
            
            txtSector.setText(med.getSector());
            txtReferencia.setText(med.getReferencia());
            txtObservacion.setText(med.getObservacion());
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtvalorConexionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorConexionKeyReleased
        /*
        try {
            txtSaldo.setText(txtvalorConexion.getText());

            float sald = Float.valueOf(txtSaldo.getText());
            if (sald == 0) {
                txtPagado.setText("SI");
            } else if (sald != 0) {
                txtPagado.setText("NO");
            }

        } catch (Exception e) {

        }
        */
    }//GEN-LAST:event_txtvalorConexionKeyReleased

    private void txtvalorConexionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorConexionKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();

            mensaje.setText("error de ingreso, ingrese digitos");
        } else {
            mensaje.setText("");
        }
    }//GEN-LAST:event_txtvalorConexionKeyTyped

    private void txtCodigoaguasobranteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoaguasobranteKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();

            mensaje.setText("error de ingreso, ingrese digitos");
        } else {
            mensaje.setText("");
        }
    }//GEN-LAST:event_txtCodigoaguasobranteKeyTyped

    private void txtSectorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSectorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSectorKeyReleased

    private void txtSectorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSectorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSectorKeyTyped

    private void txtReferenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReferenciaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReferenciaKeyReleased

    private void txtReferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReferenciaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReferenciaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonNice btnCancelar;
    private org.edisoncor.gui.button.ButtonNice btnEditar;
    private org.edisoncor.gui.button.ButtonNice btnEditar1;
    private org.edisoncor.gui.button.ButtonNice btnElimnar;
    private org.edisoncor.gui.button.ButtonNice btnGuardar;
    private org.edisoncor.gui.button.ButtonNice btnNuevo;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.ButtonGroup grupoBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JLabel label;
    public static javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblIdaguasobrante;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel mensaje;
    private javax.swing.JRadioButton rdbApellidosN;
    private javax.swing.JRadioButton rdbtodos;
    public static javax.swing.JTextField txtCodigoaguasobrante;
    public static javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObservacion;
    public static javax.swing.JTextField txtReferencia;
    public static javax.swing.JTextField txtSector;
    public static javax.swing.JTextField txtUsuarioCed;
    public static javax.swing.JTextField txtvalorConexion;
    // End of variables declaration//GEN-END:variables
}
