/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Controladores.ControlFormularios;
import Controladores.classAguasobrante;
import Controladores.classDetalleFactura;
import Controladores.classDetalleFacturasobrante;
import Controladores.classMedidor;
import Controladores.classTarifas;
import Controladores.classTarifassobrante;
import entidades.Detallefactura;
import entidades.Detallefacturasobrante;
import entidades.Medidor;
import entidades.Tarifassobrante;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class frmDetalleFacturasobrante extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmDetalleFactura
     */
    classAguasobrante cm = new classAguasobrante();
    classTarifassobrante ct = new classTarifassobrante();
    classDetalleFacturasobrante cdt = new classDetalleFacturasobrante();
    Tarifassobrante tarifasobrante = new Tarifassobrante();
    Detallefacturasobrante detallefact = new Detallefacturasobrante();
    //agregar lista de registrados el consumo

    public frmDetalleFacturasobrante() {
        initComponents();
//        Dimension desktopSize = FrmPrincipal.jDesktopPane1.getSize();
//        Dimension jInternalFrameSize = this.getSize();
//        this.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, 4);
        ct = new classTarifassobrante();
//        cdt = new classDetalleFactura();
        ct.cargarCmbTarifassobrante(combotarifas);
        tarifasobrante=ct.buscarIdTarifassobrante(1);
        lblIdDetalle.setText("");
        lblIdDetalle.setVisible(false);
//        String anMes = lblanio.getText() + "-" + lblmes.getText();
//        cm.cargarTablaMedidorDetalle(tabla, anMes);
    }
    int comienzo = 0;
//    classDetalleFactura cdf = new classDetalleFactura();
//    classMoverRegistros moverRegistros = new classMoverRegistros(cm.getMedidor());
//    classMoverRegistros moverRegistros2;
//    int mes = FrmIngresoMedidas.mchMes.getMonth() + 1;

    private void mostrar() {
        tabla.setEnabled(true);
        btnNuevo.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnElimnar.setEnabled(false);
        btnCancelar.setEnabled(true);
        jTable1.setEnabled(false);
        tabla.setEnabled(true);
    }

    private void ocultar() {
        tabla.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnElimnar.setEnabled(true);
        btnCancelar.setEnabled(false);
    }

    private void limpiar() {
        txtCodigoUsuario.setText("");
        txtrucCi.setText("");
        txtUsuario.setText("");
        txtApodo.setText("");
        txtEstado.setText("");
        txtSubTotal.setText("");
        txtTotal.setText("");
        lblIdDetalle.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnNuevo = new org.edisoncor.gui.button.ButtonNice();
        btnGuardar = new org.edisoncor.gui.button.ButtonNice();
        btnEditar = new org.edisoncor.gui.button.ButtonNice();
        btnElimnar = new org.edisoncor.gui.button.ButtonNice();
        btnCancelar = new org.edisoncor.gui.button.ButtonNice();
        mensaje = new javax.swing.JLabel();
        btnAtras = new org.edisoncor.gui.button.ButtonNice();
        jPanel1 = new javax.swing.JPanel();
        txtCodigoUsuario = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtApodo = new javax.swing.JTextField();
        combotarifas = new javax.swing.JComboBox();
        txtSubTotal = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtrucCi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblIdDetalle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtBuscarNumMedidor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblmes = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblanio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REGISTRO DE CONSUMOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/Globe.png"))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNuevo.setBackground(new java.awt.Color(0, 102, 255));
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("NUEVO");
        btnNuevo.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.ROUND_LEFT);
        btnNuevo.setSegundoColor(new java.awt.Color(0, 51, 255));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 102, 255));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setEnabled(false);
        btnGuardar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
        btnGuardar.setSegundoColor(new java.awt.Color(0, 51, 255));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 102, 255));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
        btnEditar.setSegundoColor(new java.awt.Color(0, 51, 255));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnElimnar.setBackground(new java.awt.Color(0, 102, 255));
        btnElimnar.setForeground(new java.awt.Color(255, 255, 255));
        btnElimnar.setText("ELIMINAR");
        btnElimnar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
        btnElimnar.setSegundoColor(new java.awt.Color(0, 51, 255));
        btnElimnar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimnarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 102, 255));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.ROUND_RIGHT);
        btnCancelar.setSegundoColor(new java.awt.Color(0, 51, 255));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        mensaje.setForeground(new java.awt.Color(204, 0, 0));

        btnAtras.setBackground(new java.awt.Color(0, 153, 51));
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon16x16/arrow_left.png"))); // NOI18N
        btnAtras.setText("ATRAS");
        btnAtras.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
        btnAtras.setSegundoColor(new java.awt.Color(0, 51, 255));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnElimnar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(241, 241, 241))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnElimnar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        txtCodigoUsuario.setEditable(false);

        txtUsuario.setEditable(false);

        txtApodo.setEditable(false);

        txtSubTotal.setEditable(false);

        txtTotal.setEditable(false);

        jLabel1.setText("Tarifa:");

        jLabel2.setText("Codigo usuario:");

        jLabel4.setText("Apellidos:");

        jLabel6.setText("Apodo/SobreNombre:");

        jLabel14.setText("Valor tarifa Base:                   $");

        jLabel15.setText("Total Por Consumo:                $");

        txtrucCi.setEditable(false);

        jLabel17.setText("Ruc/CI");

        jLabel18.setText("Estado:");

        txtEstado.setEditable(false);

        lblIdDetalle.setText("id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdDetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrucCi)
                    .addComponent(txtApodo)
                    .addComponent(txtUsuario)
                    .addComponent(txtCodigoUsuario)
                    .addComponent(combotarifas, 0, 178, Short.MAX_VALUE)
                    .addComponent(txtEstado))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combotarifas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrucCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.setEnabled(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel20.setText("TABLA DE USUARIOS CON SUS RESPECTIVOS MEDIDORES");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel21.setText("TABLA DE REGISTRO DE CONSUMO");

        jLabel19.setText("Codigo usuario:");

        txtBuscarNumMedidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarNumMedidorKeyTyped(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblmes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblmes.setForeground(new java.awt.Color(0, 0, 102));
        lblmes.setText("Mes");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Mes:");

        lblanio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblanio.setForeground(new java.awt.Color(0, 0, 102));
        lblanio.setText("Año");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Año:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBuscarNumMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblanio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblmes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblanio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16)
                    .addComponent(lblmes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtBuscarNumMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        mostrar();
        limpiar();
        jTable1.setEnabled(false);

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            int i = JOptionPane.showConfirmDialog(this, "¿Guardar?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                int idTar = ct.buscarTarifaDescrip(combotarifas.getSelectedItem().toString()).getIdtarifassobrante();

                int idMed = cm.buscarAguasobranteCodigo(Integer.valueOf(txtCodigoUsuario.getText())).getCodigoaguasobrante();
                String anioMes = lblanio.getText() + "-" + lblmes.getText();
                
                float sutotal = Float.valueOf(txtSubTotal.getText());
                float total = Float.valueOf(txtTotal.getText());

                if (cdt.ingresoMesMayor(idMed, Integer.valueOf(lblanio.getText()), Integer.valueOf(lblmes.getText())) == true) {
                    if (lblIdDetalle.getText().equals("")) {
                        cdt.guardarDetallefacturasobrante(idTar, idMed, anioMes, sutotal, total, "NO");
                        limpiar();
                        cdt.cargarTablaMedidorDetalle(tabla, anioMes, cdt.listaMed(anioMes));
                    } else if (!lblIdDetalle.getText().equals("")) {
                        cdt.modificarDetallefacturasobrante(Integer.valueOf(lblIdDetalle.getText()), idTar, idMed, anioMes, sutotal, total, "NO");
                        limpiar();
                    }
                }
                cdt.cargarBusquedaAnioMes(jTable1, anioMes);
                ocultar();
                limpiar();
                jTable1.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en Entrada de Datos", "Información", 1);

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        mostrar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnElimnarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimnarActionPerformed
  
        try {
            cdt.eliminarDetallefacturasobrante(Integer.valueOf(lblIdDetalle.getText()));
            String anMes = lblanio.getText() + "-" + lblmes.getText();
            cdt.cargarTablaMedidorDetalle(tabla, anMes, cdt.listaMed(anMes));
             cdt.cargarBusquedaAnioMes(jTable1, anMes);
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Proceso No Realizado!.",
                    "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnElimnarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        ocultar();
        limpiar();
        jTable1.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        try {
            limpiar();
            int n = tabla.getSelectedRow();
            txtCodigoUsuario.setText(tabla.getValueAt(n, 1).toString());
            txtrucCi.setText(tabla.getValueAt(n, 2).toString());
            txtUsuario.setText(tabla.getValueAt(n, 3).toString());
            txtApodo.setText(tabla.getValueAt(n, 4).toString());
            txtEstado.setText(tabla.getValueAt(n, 5).toString());
            
            txtSubTotal.setText(tarifasobrante.getTarifamensual().toString());
            float total =tarifasobrante.getTarifamensual()+tarifasobrante.getIva();
            txtTotal.setText(String.valueOf(total));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaKeyReleased
        // TODO add your handling code here:
        try {
            limpiar();
            int n = tabla.getSelectedRow();
            txtCodigoUsuario.setText(tabla.getValueAt(n, 1).toString());
            txtrucCi.setText(tabla.getValueAt(n, 2).toString());
            txtUsuario.setText(tabla.getValueAt(n, 3).toString());
            txtApodo.setText(tabla.getValueAt(n, 4).toString());
            txtEstado.setText(tabla.getValueAt(n, 5).toString());
            
            txtSubTotal.setText(tarifasobrante.getTarifamensual().toString());
            float total =tarifasobrante.getTarifamensual()+tarifasobrante.getIva();
            txtTotal.setText(String.valueOf(total));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_tablaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int numMed = Integer.valueOf(txtBuscarNumMedidor.getText());
            String anioMes = lblanio.getText() + "-" + lblmes.getText();
            detallefact= cdt.buscarNumAguasobranteAnioMes(numMed, anioMes);
            
            if (detallefact == null) {
                JOptionPane.showMessageDialog(null, "Datos No Encontrados", "Información", 1);
            } else {
                lblIdDetalle.setText(detallefact.getIddetallefacsobrante().toString());
                txtCodigoUsuario.setText(detallefact.getIdaguasobrante().getCodigoaguasobrante().toString());
                txtrucCi.setText(detallefact.getIdaguasobrante().getIdusuario().getRucci());
                txtUsuario.setText(detallefact.getIdaguasobrante().getIdusuario().getPrimernombre() + " "
                        + detallefact.getIdaguasobrante().getIdusuario().getSegundonombre() + " "
                        + detallefact.getIdaguasobrante().getIdusuario().getPrimerapellido() + " "
                        + detallefact.getIdaguasobrante().getIdusuario().getSegundoapellido());
                txtApodo.setText(detallefact.getIdaguasobrante().getIdusuario().getApadosn());
                txtEstado.setText(detallefact.getIdaguasobrante().getEstado());
                txtSubTotal.setText(detallefact.getSubtotal().toString());
                txtTotal.setText(detallefact.getTotal().toString());
                JOptionPane.showMessageDialog(null, "Datos Encontrados", "Información", 1);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

        FrmIngresoMedidas us = new FrmIngresoMedidas();
        ControlFormularios cf = new ControlFormularios();
        cf.ControlaInstancia(us);
        this.dispose();


    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        try {
            limpiar();
            int n = jTable1.getSelectedRow();
            int idDetalle = Integer.valueOf(jTable1.getValueAt(n, 0).toString());
            
            detallefact=cdt.buscarIdDetallefacturasobrante(idDetalle);
            //System.out.println(detallefact.getIdmedidor().getFecha());
            lblIdDetalle.setText(detallefact.getIddetallefacsobrante().toString());
            
            //cdt.cargarBusquedaAnioMesDatos(jTable1.getValueAt(n, 0).toString(),idDetalle);
            txtCodigoUsuario.setText(detallefact.getIdaguasobrante().getCodigoaguasobrante().toString());
            txtrucCi.setText(detallefact.getIdaguasobrante().getIdusuario().getRucci());
            
            
            
            txtUsuario.setText(detallefact.getIdaguasobrante().getIdusuario().getPrimernombre() + " "
                    + detallefact.getIdaguasobrante().getIdusuario().getSegundonombre() + " "
                    + detallefact.getIdaguasobrante().getIdusuario().getPrimerapellido() + " "
                    + detallefact.getIdaguasobrante().getIdusuario().getSegundoapellido());
            txtApodo.setText(detallefact.getIdaguasobrante().getIdusuario().getApadosn());
            txtEstado.setText(detallefact.getIdaguasobrante().getEstado());
            txtSubTotal.setText(detallefact.getSubtotal().toString());
            txtTotal.setText(detallefact.getTotal().toString());
            
            //combopagado.setSelectedItem(detallefact.getObservacion());

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        try {
            int n = jTable1.getSelectedRow();
            int idDetalle = Integer.valueOf(jTable1.getValueAt(n, 0).toString());
            detallefact=cdt.buscarIdDetallefacturasobrante(idDetalle);
            
            
            
            lblIdDetalle.setText(detallefact.getIddetallefacsobrante().toString());
            
            txtCodigoUsuario.setText(detallefact.getIdaguasobrante().getCodigoaguasobrante().toString());
            txtrucCi.setText(detallefact.getIdaguasobrante().getIdusuario().getRucci());
            txtUsuario.setText(detallefact.getIdaguasobrante().getIdusuario().getPrimernombre() + " "
                    + detallefact.getIdaguasobrante().getIdusuario().getSegundonombre() + " "
                    + detallefact.getIdaguasobrante().getIdusuario().getPrimerapellido() + " "
                    + detallefact.getIdaguasobrante().getIdusuario().getSegundoapellido());
            txtApodo.setText(detallefact.getIdaguasobrante().getIdusuario().getApadosn());
            txtEstado.setText(detallefact.getIdaguasobrante().getEstado());
            txtSubTotal.setText(detallefact.getSubtotal().toString());
            txtTotal.setText(detallefact.getTotal().toString());

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void txtBuscarNumMedidorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarNumMedidorKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscarNumMedidorKeyTyped
    private void setDatosMover(Medidor medidor, String descripTar) {
//        classMedidor cm = new classMedidor();
//        classusuario cu = new classusuario();
        try {
            limpiar();
            txtCodigoUsuario.setText(medidor.getNummedidor().toString());
            txtUsuario.setText(medidor.getIdusuario().getPrimerapellido() + " " + medidor.getIdusuario().getSegundoapellido());
            txtApodo.setText(medidor.getIdusuario().getApadosn());

        } catch (Exception e) {
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonNice btnAtras;
    private org.edisoncor.gui.button.ButtonNice btnCancelar;
    private org.edisoncor.gui.button.ButtonNice btnEditar;
    private org.edisoncor.gui.button.ButtonNice btnElimnar;
    private org.edisoncor.gui.button.ButtonNice btnGuardar;
    private org.edisoncor.gui.button.ButtonNice btnNuevo;
    private javax.swing.JComboBox combotarifas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JLabel lblIdDetalle;
    public static javax.swing.JLabel lblanio;
    public static javax.swing.JLabel lblmes;
    private javax.swing.JLabel mensaje;
    public static javax.swing.JTable tabla;
    private javax.swing.JTextField txtApodo;
    private javax.swing.JTextField txtBuscarNumMedidor;
    private javax.swing.JTextField txtCodigoUsuario;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtrucCi;
    // End of variables declaration//GEN-END:variables
}
