/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Controladores.ControlFormularios;
import Controladores.classMedidor;
import Controladores.classusuario;
import static Formularios.FrmPagosAsistemcia.lblfecha;
import entidadesCruds.exceptions.IllegalOrphanException;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class FrmMedidor extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmMedidor
     */
    classMedidor cm = new classMedidor();
    classusuario cu = new classusuario();

    public FrmMedidor() {
        initComponents();
        limpiar();
        Dimension desktopSize = FrmPrincipal.jDesktopPane1.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, 4);
        //cu.cargarTablaUsuario2(jTable1);.

        cm.cargarTablaMedidor(jTable1);
        ocultar();
        Date fechaActual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String hoy = formato.format(fechaActual);
        lblfecha.setText(hoy);
    }

    ControlFormularios cf;

    public void mostrar() {

        txtvalorConexion.setEnabled(true);
        txtSerie.setEditable(true);
        txtMedidor.setEditable(true);
        btnNuevo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnElimnar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        jTable1.setEnabled(false);

    }

    public void ocultar() {
        txtvalorConexion.setEnabled(false);
        txtSerie.setEditable(false);
        txtMedidor.setEditable(false);
        btnNuevo.setEnabled(true);
        btnEditar.setEnabled(true);
        btnElimnar.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        jTable1.setEnabled(true);
    }

    public void limpiar() {

        txtNombre.setText("");
        txtUsuarioCed.setText("");
        txtSerie.setText("");
        txtMedidor.setText("");
        lblIdmedidor.setText("");
        lblIdUsuario.setText("");
        txtvalorConexion.setText("");
        txtPagado.setText("");
        txtSaldo.setText("");
//        lblIdUsuario.setVisible(false);
//        jLabel8.setVisible(false);
//         lblIdmedidor.setVisible(false);
//        jLabel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBusqueda = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        btnNuevo = new org.edisoncor.gui.button.ButtonNice();
        btnGuardar = new org.edisoncor.gui.button.ButtonNice();
        btnEditar = new org.edisoncor.gui.button.ButtonNice();
        btnElimnar = new org.edisoncor.gui.button.ButtonNice();
        btnCancelar = new org.edisoncor.gui.button.ButtonNice();
        mensaje = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEditar1 = new org.edisoncor.gui.button.ButtonNice();
        lblfecha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIdmedidor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        txtMedidor = new javax.swing.JTextField();
        txtUsuarioCed = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        txtvalorConexion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPagado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }};
            jTextField1 = new javax.swing.JTextField();
            jLabel7 = new javax.swing.JLabel();
            rdbtodos = new javax.swing.JRadioButton();
            rdbApellidosN = new javax.swing.JRadioButton();

            setClosable(true);
            setIconifiable(true);
            setMaximizable(true);
            setResizable(true);
            setTitle("FORMULARIO MEDIDOR");

            jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            btnNuevo.setBackground(new java.awt.Color(0, 102, 255));
            btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
            btnNuevo.setText("NUEVO");
            btnNuevo.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.ROUND_LEFT);
            btnNuevo.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnNuevo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnNuevoActionPerformed(evt);
                }
            });

            btnGuardar.setBackground(new java.awt.Color(0, 102, 255));
            btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
            btnGuardar.setText("GUARDAR");
            btnGuardar.setEnabled(false);
            btnGuardar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
            btnGuardar.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnGuardar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGuardarActionPerformed(evt);
                }
            });

            btnEditar.setBackground(new java.awt.Color(0, 102, 255));
            btnEditar.setForeground(new java.awt.Color(255, 255, 255));
            btnEditar.setText("EDITAR");
            btnEditar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
            btnEditar.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnEditar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEditarActionPerformed(evt);
                }
            });

            btnElimnar.setBackground(new java.awt.Color(0, 102, 255));
            btnElimnar.setForeground(new java.awt.Color(255, 255, 255));
            btnElimnar.setText("ELIMINAR");
            btnElimnar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
            btnElimnar.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnElimnar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnElimnarActionPerformed(evt);
                }
            });

            btnCancelar.setBackground(new java.awt.Color(0, 102, 255));
            btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
            btnCancelar.setText("CANCELAR");
            btnCancelar.setEnabled(false);
            btnCancelar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.ROUND_RIGHT);
            btnCancelar.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelarActionPerformed(evt);
                }
            });

            mensaje.setForeground(new java.awt.Color(204, 0, 0));

            jLabel6.setText("Agregar Nuevo Usuario");

            btnEditar1.setBackground(new java.awt.Color(0, 102, 255));
            btnEditar1.setForeground(new java.awt.Color(255, 255, 255));
            btnEditar1.setText("+");
            btnEditar1.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
            btnEditar1.setSegundoColor(new java.awt.Color(0, 51, 255));
            btnEditar1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEditar1ActionPerformed(evt);
                }
            });

            lblfecha.setText("jLabel14");

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnElimnar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnElimnar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(lblfecha)))))
            );

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Medidor Nuevo"));

            jLabel1.setText("id:");

            jLabel2.setText("Cedula:");

            jLabel3.setText("Serie:");

            lblIdmedidor.setText("jLabel1");

            jLabel5.setText("N° de Medidor:");

            txtMedidor.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtMedidorKeyTyped(evt);
                }
            });

            txtUsuarioCed.setEnabled(false);
            txtUsuarioCed.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtUsuarioCedKeyTyped(evt);
                }
            });

            txtNombre.setEnabled(false);

            jLabel4.setText("Nombre:");

            comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVO", "INACTIVO" }));

            jLabel8.setText("Numero de Usuario:");

            lblIdUsuario.setText("jLabel9");

            label.setText("Estado:");

            txtvalorConexion.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    txtvalorConexionKeyReleased(evt);
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtvalorConexionKeyTyped(evt);
                }
            });

            jLabel9.setText("Monto conexion:");

            jLabel10.setText("USD");

            jLabel11.setText("Pagado:");

            txtPagado.setEditable(false);

            jLabel12.setText("Saldo:");

            txtSaldo.setEditable(false);

            jLabel13.setText("USD");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblIdmedidor))
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSerie)
                                .addComponent(txtUsuarioCed)
                                .addComponent(txtNombre)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblIdUsuario))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 1, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txtMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtSaldo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtvalorConexion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel13))))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblIdmedidor)
                        .addComponent(jLabel8)
                        .addComponent(lblIdUsuario))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtUsuarioCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label)
                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtvalorConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de usuarios existentes"));

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTable1KeyReleased(evt);
                }
            });
            jScrollPane1.setViewportView(jTable1);

            jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextField1KeyReleased(evt);
                }
            });

            jLabel7.setText("Buscar:");

            grupoBusqueda.add(rdbtodos);
            rdbtodos.setSelected(true);
            rdbtodos.setText("Todos");
            rdbtodos.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    rdbtodosActionPerformed(evt);
                }
            });

            grupoBusqueda.add(rdbApellidosN);
            rdbApellidosN.setText("Apellidos - Nombres");
            rdbApellidosN.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    rdbApellidosNActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(rdbtodos)
                    .addGap(18, 18, 18)
                    .addComponent(rdbApellidosN)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(0, 175, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addGap(46, 46, 46)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1))
                    .addGap(39, 39, 39))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbtodos)
                        .addComponent(rdbApellidosN))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        txtUsuarioCed.setEnabled(true);
        mostrar();
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        float saldo = cm.buscarMedidorNumM(Integer.valueOf(txtMedidor.getText())).getSaldo();
        if (saldo != 200) {
            txtvalorConexion.setText(saldo + "");
            txtvalorConexion.setEnabled(false);
        } else {
            txtvalorConexion.setEnabled(true);
        }
        mostrar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        ocultar();
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed

        this.setVisible(false);
        FrmUsuario us = new FrmUsuario();

        cf = new ControlFormularios();
        cf.ControlaInstancia(us);

    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {

            int idUsuario = Integer.valueOf(lblIdUsuario.getText());
            String serie = txtSerie.getText();
            int numMedidor = Integer.valueOf(txtMedidor.getText());
            String estado = comboEstado.getSelectedItem().toString();
            float valorConx = Float.valueOf(txtvalorConexion.getText());
            String pagado = txtPagado.getText();
            float saldo = Float.valueOf(txtSaldo.getText());
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                Date fechaActual = formato.parse(lblfecha.getText());
            if (lblIdmedidor.getText().equals("")) {
                int i = JOptionPane.showConfirmDialog(this, "¿Realmente desea Registrar?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    cm.guardarMedidor(idUsuario, serie, numMedidor, estado, valorConx, pagado, saldo,fechaActual);
                    cm.cargarTablaMedidor(jTable1);
                    limpiar();
                    ocultar();
                }

            } else if (!lblIdmedidor.getText().equals("")) {
                int i = JOptionPane.showConfirmDialog(this, "¿Realmente desea Modificar?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    int idmed = Integer.valueOf(lblIdmedidor.getText());
                    cm.modificarMedidor(idmed, idUsuario, serie, numMedidor, estado, valorConx, pagado, saldo);
                    cm.cargarTablaMedidor(jTable1);
                    limpiar();
                    ocultar();
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnElimnarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimnarActionPerformed
        try {
            int i = JOptionPane.showConfirmDialog(this, "¿Realmente desea Eliminar?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                cm.eliminarMedidor(Integer.valueOf(lblIdmedidor.getText()));
                cm.cargarTablaMedidor(jTable1);
                JOptionPane.showMessageDialog(null, "Eliminado");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No Se Puede Eliminar");
        }
    }//GEN-LAST:event_btnElimnarActionPerformed

    private void txtUsuarioCedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioCedKeyTyped

        if (txtUsuarioCed.getText().equals("")) {
            FrmBusqueda bu = new FrmBusqueda();
            bu.setVisible(true);
        }
    }//GEN-LAST:event_txtUsuarioCedKeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if (rdbApellidosN.isSelected() == true) {
            cm.cargarTablaApellidosNombres(jTextField1.getText(), jTable1);
        } else {
            cm.cargarTablaMedidor(jTable1);
        }

    }//GEN-LAST:event_jTextField1KeyReleased

    private void rdbtodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtodosActionPerformed
        // TODO add your handling code here:
        cm.cargarTablaMedidor(jTable1);
        jTextField1.setText("");
    }//GEN-LAST:event_rdbtodosActionPerformed

    private void rdbApellidosNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbApellidosNActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_rdbApellidosNActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        try {
            int n = jTable1.getSelectedRow();
            lblIdmedidor.setText(jTable1.getValueAt(n, 0).toString());
            txtUsuarioCed.setText(jTable1.getValueAt(n, 1).toString());
            txtNombre.setText(jTable1.getValueAt(n, 2).toString());

            txtMedidor.setText(cu.buscarUsuarioRucCi(txtUsuarioCed.getText()).getIdusuario().toString());

            txtSerie.setText(jTable1.getValueAt(n, 4).toString());
            comboEstado.setSelectedItem(jTable1.getValueAt(n, 5).toString());
            lblIdUsuario.setText(cu.buscarUsuarioRucCi(txtUsuarioCed.getText()).getIdusuario().toString());
            txtUsuarioCed.setEnabled(false);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try {
            int n = jTable1.getSelectedRow();
            int numM = Integer.valueOf(jTable1.getValueAt(n, 6).toString());

            lblIdmedidor.setText(jTable1.getValueAt(n, 0).toString());
            txtUsuarioCed.setText(jTable1.getValueAt(n, 1).toString());
            txtNombre.setText(jTable1.getValueAt(n, 2).toString());

            //txtMedidor.setText(cu.buscarUsuarioRucCi(txtUsuarioCed.getText()).getIdusuario().toString());
            txtMedidor.setText(jTable1.getValueAt(n, 6).toString());
            txtSerie.setText(jTable1.getValueAt(n, 4).toString());
            comboEstado.setSelectedItem(jTable1.getValueAt(n, 5).toString());
            lblIdUsuario.setText(cu.buscarUsuarioRucCi(txtUsuarioCed.getText()).getIdusuario().toString());
            txtUsuarioCed.setEnabled(false);
            txtvalorConexion.setText(cm.buscarMedidorNumM(numM).getValorporconexion().toString());
            txtPagado.setText(cm.buscarMedidorNumM(numM).getPagado().toString());
            txtSaldo.setText(cm.buscarMedidorNumM(numM).getSaldo().toString());
            //System.out.println(cm.buscarMedidorNumM(jTable1.getValueAt(n, 0).toString()));

        } catch (Exception e) {
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtvalorConexionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorConexionKeyReleased
        try {
            txtSaldo.setText(txtvalorConexion.getText());

            float sald = Float.valueOf(txtSaldo.getText());
            if (sald == 0) {
                txtPagado.setText("SI");
            } else if (sald != 0) {
                txtPagado.setText("NO");
            }

        } catch (Exception e) {

        }

    }//GEN-LAST:event_txtvalorConexionKeyReleased

    private void txtvalorConexionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorConexionKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();

            mensaje.setText("error de ingreso, ingrese digitos");
        } else {
            mensaje.setText("");
        }
    }//GEN-LAST:event_txtvalorConexionKeyTyped

    private void txtMedidorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedidorKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();

            mensaje.setText("error de ingreso, ingrese digitos");
        } else {
            mensaje.setText("");
        }
    }//GEN-LAST:event_txtMedidorKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonNice btnCancelar;
    private org.edisoncor.gui.button.ButtonNice btnEditar;
    private org.edisoncor.gui.button.ButtonNice btnEditar1;
    private org.edisoncor.gui.button.ButtonNice btnElimnar;
    private org.edisoncor.gui.button.ButtonNice btnGuardar;
    private org.edisoncor.gui.button.ButtonNice btnNuevo;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.ButtonGroup grupoBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JLabel label;
    public static javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblIdmedidor;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel mensaje;
    private javax.swing.JRadioButton rdbApellidosN;
    private javax.swing.JRadioButton rdbtodos;
    public static javax.swing.JTextField txtMedidor;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtPagado;
    public static javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSerie;
    public static javax.swing.JTextField txtUsuarioCed;
    public static javax.swing.JTextField txtvalorConexion;
    // End of variables declaration//GEN-END:variables
}
