/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Controladores.ControlFormularios;
import Controladores.classCorte;
import Controladores.classDetalleFactura;
import Controladores.classFactura;
import Controladores.classMedidor;
import Controladores.classOtrosPagos;
import Controladores.classPagosNuevoMed;
import static Formularios.FrmFactura.*;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class FrmOtrosPagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmOtrosPagos
     */
    classCorte cc = new classCorte();
    classMedidor cm = new classMedidor();
    ControlFormularios cf = new ControlFormularios();
    classDetalleFactura cdf = new classDetalleFactura();
    classFactura cft = new classFactura();
    classPagosNuevoMed cpnm = new classPagosNuevoMed();

    public FrmOtrosPagos() {
        initComponents();
        inicio();
//        cc = new classCorte();
//        cc.cargarCorte(jTable1);
    }
    classOtrosPagos otros;

    private void inicio() {
        Dimension desktopSize = FrmPrincipal.jDesktopPane1.getSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, 4);
        otros = new classOtrosPagos();
        cc.cargarCorte2(jTable1);
    }

    private void mostrar() {
        txtDerecho.setEnabled(true);
        txtInteres.setEnabled(true);
//        txtSerie.setEnabled(true);

//        btnGuardar.setEnabled(true);
//        btnEditar.setEnabled(false);
//        btnCancelar.setEnabled(true);
    }

    private void ocultar() {
        txtDerecho.setEnabled(false);
        txtInteres.setEnabled(false);
    }

    private void limpiar() {
        txtDerecho.setText("");
        txtInteres.setText("");
        txtIdCorte.setText("");
        txtMedidor.setText("");
        txtArea.setText("");
        txtMulta.setText("");
        txtTotal.setText("");
        txtCedula.setText("");
    }
    String idCorte;
    float derecho;
    String multaR;
    String multaMS;
    String interes;
    String serie;
    String usuario;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new org.edisoncor.gui.button.ButtonNice();
        btnEditar = new org.edisoncor.gui.button.ButtonNice();
        btnCancelar = new org.edisoncor.gui.button.ButtonNice();
        mensaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMedidor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtIdCorte = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        panelReconexion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMulta = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDerecho = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtInteres = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 =  new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REALIZAR OTROS PAGOS");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGuardar.setBackground(new java.awt.Color(0, 102, 0));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("REALIZAR PAGO");
        btnGuardar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.ROUND_LEFT);
        btnGuardar.setSegundoColor(new java.awt.Color(0, 51, 255));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 102, 255));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.RECT);
        btnEditar.setSegundoColor(new java.awt.Color(0, 51, 255));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 102, 255));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setModelo(org.edisoncor.gui.button.ButtonNice.Modelo.ROUND_RIGHT);
        btnCancelar.setSegundoColor(new java.awt.Color(0, 51, 255));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        mensaje.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("id:");

        jLabel3.setText("id Corte:");

        jLabel2.setText("Medidor N°:");

        txtMedidor.setEnabled(false);

        jLabel9.setText("Cedula:");

        txtCedula.setEnabled(false);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane3.setViewportView(txtArea);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("TOTAL:");
        jLabel11.setToolTipText("Valor total a pagar");

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        panelReconexion.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Reconexion de corte"));

        jLabel5.setText("Multa Reconexion:");

        txtMulta.setEnabled(false);

        jLabel22.setText("USD");

        jLabel4.setText("Derecho Conexion:");

        txtDerecho.setEnabled(false);
        txtDerecho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDerechoKeyReleased(evt);
            }
        });

        jLabel23.setText("USD");

        jLabel7.setText("Interes:");

        txtInteres.setToolTipText("Ingrese numero entero");
        txtInteres.setEnabled(false);
        txtInteres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInteresKeyReleased(evt);
            }
        });

        jLabel13.setText("% ej: 12");

        javax.swing.GroupLayout panelReconexionLayout = new javax.swing.GroupLayout(panelReconexion);
        panelReconexion.setLayout(panelReconexionLayout);
        panelReconexionLayout.setHorizontalGroup(
            panelReconexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReconexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReconexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReconexionLayout.createSequentialGroup()
                        .addGroup(panelReconexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(68, 68, 68)
                        .addGroup(panelReconexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txtMulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelReconexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)))
                    .addGroup(panelReconexionLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(121, 121, 121)
                        .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReconexionLayout.setVerticalGroup(
            panelReconexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReconexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReconexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReconexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReconexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("USD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelReconexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtIdCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addComponent(txtMedidor)))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(txtIdCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(panelReconexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de usuarios con corte"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setUpdateSelectionOnSort(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {
            this.dispose();
            FrmFactura as = new FrmFactura();
            cf = new ControlFormularios();
            cf.ControlaInstancia(as);
            if (cm.buscarMedidorNumM(Integer.valueOf(txtMedidor.getText())).getSaldo() > 0) {
                FrmFactura.comboPagos.removeAllItems();
                FrmFactura.comboPagos.setVisible(true);
                for (int i = 0; i < cm.buscarMedidorNumM(Integer.valueOf(txtMedidor.getText())).getSaldo() + 1; i++) {
                    FrmFactura.comboPagos.addItem(i + ".0");
                }
                FrmFactura.lbldescNuevoMed.setText("Cuotas Pagadas: " + cpnm.numCuotas(cm.buscarMedidorNumM(Integer.valueOf(txtMedidor.getText())).getIdmedidor()) + " Saldo Faltantate por Conexion: "
                        + cm.buscarMedidorNumM(Integer.valueOf(txtMedidor.getText())).getSaldo().toString());
//            txtPagoNuevoMed.setText(cm.buscarMedidorNumM(Integer.valueOf(txtnumMedidor.getText())).getSaldo().toString());
            } else {
                FrmFactura.lbldescNuevoMed.setText("");
                FrmFactura.comboPagos.setVisible(false);
            }
//            FrmFactura.tablaOtros.setValueAt(txtTotal.getText(), 0, 1);
            FrmFactura.txtnumMedidor.setText(txtMedidor.getText());
            FrmFactura.txtnumMedidor.setEnabled(false);
       
//            FrmFactura.tablaOtros.setVisible(true);
//            FrmFactura.btnMasDetalles.setVisible(true);

            try {

                if (cdf.buscarNumMedDetallefactura(Integer.valueOf(txtnumMedidor.getText())).equals(null)) {
                } else {
                    FrmFactura.jLabel2.setText(String.valueOf(cft.numFactura()));
                    int numMed = Integer.valueOf(FrmFactura.txtnumMedidor.getText());
                    String ruc = cdf.buscarNumMedDetallefactura(numMed).getIdmedidor().getIdusuario().getRucci();
                    String client = cdf.buscarNumMedDetallefactura(numMed).getIdmedidor().getIdusuario().getPrimerapellido() + " "
                            + cdf.buscarNumMedDetallefactura(numMed).getIdmedidor().getIdusuario().getSegundoapellido() + " "
                            + cdf.buscarNumMedDetallefactura(numMed).getIdmedidor().getIdusuario().getPrimernombre() + " "
                            + cdf.buscarNumMedDetallefactura(numMed).getIdmedidor().getIdusuario().getSegundonombre() + " ";
                    String direccioN = cdf.buscarNumMedDetallefactura(numMed).getIdmedidor().getIdusuario().getDireccion();
                    FrmFactura.txtRuc.setText(ruc);
                    FrmFactura.txtCliente.setText(client);
                    cdf.tablaDetalles(FrmFactura.jTable1, numMed);
                    FrmFactura.txtdireccion.setText(direccioN);
                    cdf.graficador(Integer.valueOf(FrmFactura.txtnumMedidor.getText()));
                    FrmFactura.txtIdCorte.setText(txtIdCorte.getText());
                    FrmFactura.txtMultaReconexion.setText(txtMulta.getText());
//                    FrmFactura.txtDerecho.setText(txtDerecho.getText());
//                    FrmFactura.txtInteres.setText(txtInteres.getText());

                }
            } catch (Exception e) {
            }

//            idCorte = txtIdCorte.getText();
//            derecho = Float.valueOf(txtDerecho.getText());
//            multaR = txtMulta.getText();
//            interes = txtInteres.getText();
//            usuario = "";
//            otros = new classOtrosPagos();
//            otros.guardarOtrospagos(Integer.valueOf(idCorte), derecho, Float.valueOf(multaR),
//                    Float.valueOf(interes),
//                    Float.valueOf(txtTotal.getText()), usuario);
//            ocultar();
//            otros.cargarTablaOtros(jTable2);
//            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        mostrar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        ocultar();
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        try {
        limpiar();
        int n = jTable1.getSelectedRow();

//        if (label.getText().equals("1")) {
        txtIdCorte.setText(cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getIdcorte().toString());
        txtMedidor.setText(cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getIdmedidor().getNummedidor().toString());
        txtMulta.setText(cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getMulta().toString());
        txtCedula.setText(cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getIdmedidor().getIdusuario().getRucci());
        String usuario = cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getIdmedidor().getIdusuario().getPrimernombre() + " "
                + cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getIdmedidor().getIdusuario().getPrimerapellido() + " "
                + cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getIdmedidor().getIdusuario().getSegundoapellido();
        String apodo = cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getIdmedidor().getIdusuario().getApadosn();
        String dir = cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getIdmedidor().getIdusuario().getDireccion();
        String sec = cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getIdmedidor().getIdusuario().getSector();
        String ref = cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getIdmedidor().getIdusuario().getReferencia();
        txtArea.setText("Nombre: " + usuario + "\nApodo: " + apodo + "\nDireccion: " + dir + "\nSector: " + sec + "\nReferencia: " + ref);

        txtTotal.setText(cc.buscarMedidorNumM(Integer.valueOf(jTable1.getValueAt(n, 0).toString())).getMulta().toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtDerechoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDerechoKeyReleased
        try {
            float mulRec = Float.valueOf(txtMulta.getText());
            float derRec = 0;
            float inte = 0;
            float subtotal = 0;
            if (txtInteres.getText().equals("") && txtDerecho.getText().equals("")) {
                derRec = 0;
                inte = 0;
                txtTotal.setText(mulRec + " usd");
            }
            if (txtInteres.getText().equals("")) {
                inte = 0;
                derRec = Float.valueOf(txtDerecho.getText());
            } else if (!txtInteres.getText().equals("")) {
                derRec = Float.valueOf(txtDerecho.getText());
                inte = Float.valueOf(txtInteres.getText()) / 100;
            }

            subtotal = (mulRec + derRec) * inte;
            float total = mulRec + derRec + subtotal;

            txtTotal.setText(total + "");
        } catch (Exception e) {
        }

    }//GEN-LAST:event_txtDerechoKeyReleased

    private void txtInteresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInteresKeyReleased
        try {
            float mulRec = Float.valueOf(txtMulta.getText());
            float derRec = 0;
            float inte = 0;
            float subtotal = 0;
            if (txtInteres.getText().equals("") && txtDerecho.getText().equals("")) {
                derRec = 0;
                inte = 0;
                txtTotal.setText(mulRec + "");
            }
            if (txtInteres.getText().equals("")) {
                inte = 0;
            }
//            if(!txtInteres.getText().equals("")){
//                inte = Float.valueOf(txtInteres.getText())/100;
//            }
            if (txtDerecho.getText().equals("")) {
                derRec = 0;
                inte = Float.valueOf(txtInteres.getText()) / 100;
            }
            if (!txtDerecho.getText().equals("")) {
                derRec = Float.valueOf(txtDerecho.getText());
                inte = Float.valueOf(txtInteres.getText()) / 100;

            }

            subtotal = (mulRec + derRec) * inte;
            float total = mulRec + derRec + subtotal;

            txtTotal.setText(total + "");
        } catch (Exception e) {
        }

    }//GEN-LAST:event_txtInteresKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonNice btnCancelar;
    private org.edisoncor.gui.button.ButtonNice btnEditar;
    private org.edisoncor.gui.button.ButtonNice btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel panelReconexion;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDerecho;
    private javax.swing.JLabel txtIdCorte;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtMedidor;
    private javax.swing.JTextField txtMulta;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
